#!/bin/bash
if [[ $1 == *"nvidia"* ]]; then
    if [ "$2" == "prepare" ]; then
        action="stop"
    elif [ "$2" == "release" ]; then
        action="start"
        nvidia-smi --persistence-mode=1
    else
        exit 0
    fi
else
    exit 0
fi

containers=$(sudo docker ps | awk '{if(NR>1) print $NF}')

# loop through all containers
for container in $containers
do
  if [ $(docker inspect --format='{{.HostConfig.Runtime}}' $container) = nvidia ]; then 
    if [ $action = "stop" ]; then 
        /usr/bin/logger "Running virtual machine with NVIDIA GPU detected, stopping '$container' docker container" -t NvidiaToggle
    elif [ $action = "start" ]; then 
        /usr/bin/logger "Virtual machine with NVIDIA GPU no longer running, starting '$container' docker container" -t NvidiaToggle
    fi
    docker $action $container
  fi
done